In [2]:
import numpy as np

In [2]:
mylilst = [1, 2, 3]

In [3]:
type(mylist)

NameError: name 'mylist' is not defined

In [4]:
type(mylilst|) # ошибка))

SyntaxError: invalid syntax (2986752547.py, line 1)

In [5]:
type(mylilst)

list

In [6]:
np.array(mylilst)

array([1, 2, 3])

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5) # из нулей

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((4, 4, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [16]:
np.linspace(0, 10, 21) # список из 21 числа, равноудаленных друг от друга в диапозоне [0, 10]

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(4, 4)

array([[0.24584751, 0.62201663, 0.90106752, 0.3839342 ],
       [0.07692112, 0.95033584, 0.86289336, 0.53495468],
       [0.43831126, 0.89007764, 0.10623881, 0.12503424],
       [0.61776803, 0.83237127, 0.14540534, 0.86952855]])

In [23]:
np.random.randn(4, 4)

array([[ 1.38948845, -0.36289703,  0.41767071,  0.78496259],
       [ 0.39238705, -0.21041637,  0.05337831, -0.28925545],
       [ 0.8161622 ,  0.16758043,  0.36499487,  0.15143939],
       [-0.56284456, -0.8432069 , -1.8311801 , -0.74085129]])

In [26]:
np.random.randint(0, 101, (5, 5))

array([[ 8, 77, 84, 16, 62],
       [68, 33, 61, 95, 14],
       [97, 80, 62, 99, 81],
       [45, 26, 38, 21, 81],
       [ 4, 58, 85,  0, 25]])

In [27]:
np.random.seed(42) # для определенного набора случайных чисел
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
arr = np.arange(0, 25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
randarr = np.random.randint(0, 101, 10)
randarr

array([ 8, 79, 94,  9, 26,  4, 33, 91, 34,  8])

In [4]:
randarr.min()

4

In [5]:
randarr.argmin() # индекс минимального элемента

5

In [37]:
randarr.dtype

dtype('int32')

In [38]:
randarr.shape

(10,)

In [41]:
randarr = randarr.reshape(5, 2)

In [42]:
randarr.shape

(5, 2)

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[6]

6

In [46]:
arr[1:4]

array([1, 2, 3])

In [47]:
arr[:3]

array([0, 1, 2])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[-5:]

array([ 6,  7,  8,  9, 10])

In [51]:
arr[1:3] = 4

In [52]:
arr

array([ 0,  4,  4,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [54]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d[0]

array([ 5, 10, 15])

In [57]:
arr_2d[1][1] == arr_2d[1, 1]

True

In [58]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [59]:
arr = np.arange(1, 11)

In [60]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [61]:
bool_array = arr > 4

In [64]:
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
arr[arr > 3] # выборка элементов по условию

array([ 4,  5,  6,  7,  8,  9, 10])

In [66]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr + 6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [68]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr ** arr

array([         1,          4,         27,        256,       3125,
            46656,     823543,   16777216,  387420489, 1410065408])

In [70]:
arr.sum()

55

In [71]:
arr.mean() # среднее

5.5

In [72]:
arr.var() # дисперсия

8.25

In [73]:
arr.std() # среднее квадратичное

2.8722813232690143

In [74]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr = arr.reshape(5, 2)

In [76]:
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [77]:
arr.sum(axis=0) # сумма колонок

array([25, 30])

In [78]:
arr.sum(axis=1) # сумма строк

array([ 3,  7, 11, 15, 19])